[[main]]
name = "Advisory"
pageRef = "advisory"
weight = 20

[[main]]
name = "Technical Insights"
pageRef = "insights"
weight = 30

[[main]]
name = "Talks"
pageRef = "talks"
weight = 40

[[main]]
name = "Publications"
pageRef = "publications"
weight = 50

[[main]]
name = "Gallery"
pageRef = "gallery"
weight = 60

[[footer]]
name = "Technical Insights"
pageRef = "insights"
weight = 10

[[footer]]
name = "Talks"
pageRef = "talks"
weight = 20

[[footer]]
name = "Gallery"
pageRef = "gallery"
weight = 30
